name: Tests

on:
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        run: |
          curl -fsS https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --only main --only test -vvv

      - name: Test
        run: |
          poetry run coverage run -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3